spring :
  datasource :
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/xtest\
               ?useUnicode=true&characterEncoding=UTF-8\
               &serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull\
               &useSSL=false"
    username: root
    password: csk110110
  devtools:
    restart:
      enabled: true

